name: Android CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:                   # Defines the jobs in this workflow
  test:                 # Job name = "test"
    runs-on: ubuntu-latest   # The environment (OS) where the job runs

    steps:              # Sequence of tasks (steps) in the job
      - name: Checkout code
        uses: actions/checkout@v4
        # This downloads your repository code into the runner so it can be built/tested

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        # This installs Java 17 (Temurin distribution) which Gradle needs to run

      - name: Run Unit Tests
        run: ./gradlew test
        # Runs Gradle’s "test" task → executes all unit tests in the project